### PR TITLE
Feature/associate system hook with host

### PR DESCRIPTION
**Pull request by CWDN**
This now adds a host id to a GitLab instance.

You'll need to run `php artisan migrate:refresh --seed`

To test:
1. Register a GitLab instance using `php artisan setup` or `php artisan register`
2. Check a system hook has been added to your GitLab with the correct structure `{appName}/{hostId/hooks/catch`
3. Create a project and the hooks should automatically added to it with the same structure as the system hook

### CODE REVIEW

**Comment by datkinson** [comment]
2 problems:
- If I don't specify a port when trying to register the gitlab url it errors, even if i'm using a hostname e.g. https://git.noprobe.co.uk

```
 [ErrorException]       
  Undefined index: port 
```
- Once I specify a port I get the following error trying to register a hook:

```
[GuzzleHttp\Exception\ClientException]                                                                
  Client error: `POST https://git.noprobe.co.uk//api/v3/hooks` resulted in a `404 Not Found` response:  
  {"message":"404 Not Found"}     
```

**Comment by datkinson** [comment]
Port issue is fixed :)

**Comment by CWDN** [comment]
Still getting Guzzle problem?

**Comment by datkinson** [comment]
Yes

**Comment by CWDN** [comment]
Could you try manually POSTing to the same url with something like postman?

**Comment by datkinson** [comment]
Still the same error

When using postman I get 401 not 404

**Comment by datkinson** [comment]
Works on http but gets 404 on https

**Pull request merged**
