### PR TITLE
Feature/ssh keys

### PR DESCRIPTION
**Pull request by datkinson**
New folder `.docker/builds` for putting docker files in.
These will be used by docker compose to build the dependant containers.
This way we can do in-project tweaks to containers for our needs.

Also as part of the ssh container I have pre-generated some keys, this key is loaded in as part of the seeder so the application has one in its database to test with.

**Note**
Travis should now be using docker-compose and is now running under production-ready settings

### CODE REVIEW

**Comment by CWDN** [comment]
```
lumen.ERROR: exception 'ErrorException' with message 'Undefined variable: file' in /var/www/app/Pipeline/Execution/Executors/SSHExecutor.php:85
```

If you are not using file based ssh auth

**Comment by datkinson** [comment]
How strange. I didn't get this issue.

**Comment by CWDN** [comment]
Makes sense though as $file is only declared if you have key based auth

**Comment by datkinson** [comment]
Oh I've clearly arranged it badly

**Comment by CWDN** [comment]
Also I've worked out why you were getting 

```
lumen.ERROR: exception 'ErrorException' with message 'ssh2_auth_pubkey_file(): Authentication failed for  using public key: Unable to open public key file' in /var/www/vendor/herzult/php-ssh/src/Ssh/Authentication/PublicKeyFile.php:47
```

It's because you are deleting the key before running any commands. It seems to actually only read the key file when you want to run commands.

Maybe add a clean up funciton?

**Comment by datkinson** [comment]
Aha! Magic

**Comment by CWDN** [comment]
Tried it by commenting out the delete and get this:

```
lumen.ERROR: exception 'ErrorException' with message 'ssh2_auth_pubkey_file(): Authentication failed for  using public key: Username/PublicKey combination invalid' in /var/www/vendor/herzult/php-ssh/src/Ssh/Authentication/PublicKeyFile.php:47
```

Ah you can only associate, one type of credentials to a auth, so when you do `$auth->credentials->username` it's returning null

:smile:

**Comment by datkinson** [comment]
Have you got your username and password set in your env file?

**Comment by datkinson** [comment]
Wait... Public key file?
Password auth shouldn't use that

**Comment by CWDN** [comment]
Yeah this is using public key

**Comment by datkinson** [comment]
Shouldn't be if its password auth

**Comment by CWDN** [comment]
I've made it use the key based auth to see what's going on. What's the username for the key?

**Comment by datkinson** [comment]
Should be the same as the demo one "knockknock"

**Comment by CWDN** [comment]
Nope, same error:

```
lumen.ERROR: exception 'ErrorException' with message 'ssh2_auth_pubkey_file(): Authentication failed for knockknock using public key: Username/PublicKey combination invalid' in /var/www/vendor/herzult/php-ssh/src/Ssh/Authentication/PublicKeyFile.php:46
```

**Comment by datkinson** [comment]
Don't know why it's asking for public key

**Pull request merged**
